services:
  node:
    image: tugboatqa/node:current-bullseye
    expose: 3000
    commands: 
      init:
         npm install
      start: 
        - npm start --prefix ${TUGBOAT_ROOT} &
         

